### ISSUE TITLE
Add translation language file installation will be an error

### ISSUE THREAD

**Issue by findxon** [TeemIp/teemip-standalone#3]
I added the translation language version file, the installation error is why, I need to modify those places, the error code is as follows。

Parse error:  syntax error, unexpected token ";", expecting "]" in /var/www/html/web/setup/modelfactory.class.inc.php(925) : eval()'d code on line 68
PHP error occured : msg=syntax error, unexpected token ";", expecting "]", no=4, file=/var/www/html/web/setup/modelfactory.class.inc.php(925) : eval()'d code, line=68

**Comment by xtophe38** [comment]
I don't understand wht you are tyring to do. Add a new language to TeemIP ? Could you, please, clarify ?

**Comment by findxon** [comment]
Yes Add a new language to TeemIP

**Comment by xtophe38** [comment]
As you probably know, the correct way to do it is to add dictionnary files in all extensions that you wnat to translate. Your error probably points a syntax error within one of these file.

This being said, would you agree to share your work with TeemIP community ? If yes, then push your files through PRs or send them to medirectly and I'll add them from my end. Thanks in advance.

**Comment by findxon** [comment]
@xtophe38 [zh_cn.dict.zip](https://github.com/TeemIp/teemip-standalone/files/13342700/zh_cn.dict.zip)
I translated all the extension dictionary files, and then put the files into the corresponding directory for installation, there was an error sent above. I don't know what the problem is, please help me to see if there is a problem with the file. There is another question I would like to ask if there is any other Settings that need to be configured after translating the file and copying it to the corresponding directory.

**Comment by xtophe38** [comment]
Many thanks ! I'll look at your files asap. Just one first comment: try to put the teemip files under the dict directory of the corresponding extension and run a setup again.

**Comment by xtophe38** [comment]
I just reviewed your files through my dev environement and I managed to spot errors in zh_cn dict files for teemip-ip-mgmt, teemip-request-mgt and teemip-zone-mgt modules. I've corrected them (from a PHP point a vue) and I've commited them to their respective directories.

So, now, the different extensions are up to date with the zh_cn translations. The standalone product will be updated with next revision. Until then, you can manually copy the translation files to the correct directories.

**Comment by findxon** [comment]
Thank you very much for your correction

**Comment by xtophe38** [comment]
You're welcome. As extensions keep evolve, don't hesitate to update the different translation files. You may, then, update the project through PRs or send the files to me.
