### ISSUE TITLE
Grant Matrix text not visible in Dark Moon theme.

### ISSUE THREAD

**Issue by mr37234** [TeemIp/teemip-standalone#4]
When you switch to the Dark Moon theme. the Yes/No values in the Grant Matrix are white on white. If you highlight them you can see that the values are there, just unable to view due to the white background.

**Comment by xtophe38** [comment]
Agreed. What saves you (a bit) is that 'Yes' are within green boxes and 'No' within red boxes but the contrast between the two remains low. Unfortunately, there is nothing much that I can do about as this part is fully inherited form the [iTop ](https://github.com/Combodo/iTop) framework... where you may leave a comment if you wish.

**Comment by xtophe38** [comment]
I'm closing the issue as it is an iTop one.
